# Generated by Django 4.0.3 on 2022-09-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
