# Generated by Django 4.0.3 on 2022-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_review_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
