# Generated by Django 4.0.3 on 2022-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_review_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
